## Tmux configuration
## -------------------------------------------------------------------------------------------------

# Disable omz automatically title change when running a command or printing the prompt.
# https://github.com/ohmyzsh/ohmyzsh/wiki/Settings/#disable_auto_title
set-environment -g DISABLE_AUTO_TITLE true

# Enables mouse reporting in tmux. Do I need this?
# Previously was broken in iTerm: https://gitlab.com/gnachman/iterm2/-/issues/12419
# Disable - copying from antigravity is less convenient.
# set -g -q mouse on

## Colors
## -------------------------------------------------------------------------------------------------

# Also see
# https://gitlab.com/gnachman/iterm2/-/wikis/tmux-Integration-Best-Practices#italics-show-up-as-reverse-video-whole-screen-reverse-video-isnt-working-or-my-term-variable-is-not-what-i-wish
set -g default-terminal "tmux-256color"

# True colors:
#
# The old way to enable true colors:
# set -ga terminal-overrides ",xterm-256color:Tc"
#
# The new way, tmux > 3.2:
# set -as terminal-features ",xterm-256color:RGB"
#
# However - even this shouldn't be needed: modern terminals set COLORTERM=truecolor.


## iTerm2 tmux integration
## -------------------------------------------------------------------------------------------------

# Tmux tab titles in iTerm2.
# See:
# - https://iterm2.com/documentation-tmux-integration.html
# - https://gitlab.com/gnachman/iterm2/-/wikis/tmux-Integration-Best-Practices

# https://gitlab.com/gnachman/iterm2/-/wikis/tmux-Integration-Best-Practices#i-want-to-see-tmux-window-titles-as-tabwindow-titles-in-iterm2
set -g set-titles on
set -g set-titles-string '[#S:#W]'

# This is needed for iTerm2 shell integration to work.
# https://gitlab.com/gnachman/iterm2/-/wikis/tmux-Integration-Best-Practices#shell-integration-and-iterm2-utilities-broke-in-tmux-33
set-option -g allow-passthrough on


## Unsorted notes below
## -------------------------------------------------------------------------------------------------

# set -g xterm-keys on

# set -g default-terminal "screen-256color"
# set -g allow-rename "screen-256color"
# set-window-option -g automatic-rename off
# set -g status-left "[#S] "

# key binding explained
# https://stackoverflow.com/questions/18600188/home-end-keys-do-not-work-in-tmux

# max pane issue
# try logging?
# https://gitlab.com/gnachman/iterm2/-/issues/12482

# looks like width issue broken - swapped row/col
# https://gitlab.com/gnachman/iterm2/-/issues/12444
# https://gitlab.com/gnachman/iterm2/-/issues/12505
# https://gitlab.com/gnachman/iterm2/-/commit/f34c6bc7cf417f270a125213a372729058d32ee0


# https://github.com/tmux/tmux/wiki/Modifier-Keys#extended-keys
# set -g xterm-keys on
# set -s extended-keys on
# set -as terminal-features 'xterm*:extkeys'
# set -g default-terminal "xterm-256color"
